import { useEffect, useMemo, useState } from 'react';

export type CatalogTile = { id:string; name:string; shortName:string|null; brand:string|null; colors:string[]; sizes:string[]; surfaces:string[]; designs:string[]; hex:string; previewUrl:string|null; imageUrls:string[]; imageCount:number; isFavorite:boolean };
const FAVORITES_KEY = 'tt_tile_favorites_v1';
const csrf = () => document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content || window.parent?.document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content || '';
function localFavorites() { try { return new Set<string>(JSON.parse(localStorage.getItem(FAVORITES_KEY) || '[]')); } catch { return new Set<string>(); } }

export function SharedTileLibrary({ activeTileId, disabled, onSelect }: { activeTileId?:string; disabled:boolean; onSelect:(tile:CatalogTile)=>void }) {
  const [tiles,setTiles]=useState<CatalogTile[]>([]); const [authenticated,setAuthenticated]=useState(false); const [favorites,setFavorites]=useState(localFavorites); const [query,setQuery]=useState(''); const [brand,setBrand]=useState(''); const [loading,setLoading]=useState(true);
  useEffect(() => { fetch('/api/catalog/tiles.php').then((r)=>r.json()).then((data)=>{ const next=data.items||[]; setTiles(next); setAuthenticated(Boolean(data.authenticated)); if(data.authenticated) setFavorites(new Set(next.filter((tile:CatalogTile)=>tile.isFavorite).map((tile:CatalogTile)=>tile.id))); }).finally(()=>setLoading(false)); },[]);
  const brands=useMemo(()=>[...new Set(tiles.map((tile)=>tile.brand).filter(Boolean) as string[])].sort(),[tiles]);
  const visible=useMemo(()=>tiles.filter((tile)=>{ const text=`${tile.name} ${tile.shortName||''} ${tile.brand||''}`.toLocaleLowerCase('ru'); return (!query||text.includes(query.toLocaleLowerCase('ru'))) && (!brand||tile.brand===brand); }).sort((a,b)=>Number(favorites.has(b.id))-Number(favorites.has(a.id))||(a.shortName||a.name).localeCompare(b.shortName||b.name,'ru')),[tiles,query,brand,favorites]);
  async function toggleFavorite(tileId:string) { const adding=!favorites.has(tileId); const next=new Set(favorites); adding?next.add(tileId):next.delete(tileId); setFavorites(next); localStorage.setItem(FAVORITES_KEY,JSON.stringify([...next])); await fetch('/api/favorites/index.php',{method:adding?'PUT':'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf:csrf(),entityType:'tile',entityId:tileId})}); }
  return <div className="shared-tile-library"><div className="shared-tile-filters"><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Поиск плитки"/><select value={brand} onChange={(event)=>setBrand(event.target.value)}><option value="">Все бренды</option>{brands.map((item)=><option key={item}>{item}</option>)}</select></div>{loading?<p className="shared-tile-status">Загрузка медиатеки…</p>:<div className="shared-tile-grid">{visible.map((tile)=><article className={activeTileId===tile.id?'shared-tile-card active':'shared-tile-card'} key={tile.id}><button type="button" className={favorites.has(tile.id)?'shared-tile-heart active':'shared-tile-heart'} onClick={()=>void toggleFavorite(tile.id)} aria-label="Избранное">{favorites.has(tile.id)?'♥':'♡'}</button><button type="button" className="shared-tile-select" disabled={disabled} onClick={()=>onSelect(tile)}>{tile.previewUrl?<img src={tile.previewUrl} alt=""/>:<span style={{background:tile.hex}}/>}<strong>{tile.shortName||tile.name}</strong><small>{tile.sizes[0]||'размер не указан'} · {tile.imageCount||tile.imageUrls?.length||1} рисунков</small></button></article>)}</div>}{!disabled?null:<small className="shared-tile-status">Сначала выберите пол, стену или зону</small>}</div>;
}
