(() => {
  const root = document.querySelector('[data-media-catalog]'); if (!root) return;
  const $ = (id) => document.getElementById(id); const csrf = document.querySelector('meta[name="csrf-token"]')?.content || '';
  const FOLDERS_KEY = 'tt_media_folders_v1';
  const state = { items: [], facets: {}, filters: { brand:'', colors:'', sizes:'', surfaces:'', designs:'' }, authenticated: false, favorites: new Set(), folders: [], folderTiles: {}, activeFolder: 'all', selectedTileId: null };
  function readLocal(key, fallback) { try { return JSON.parse(localStorage.getItem(key) || '') || fallback; } catch { return fallback; } }
  function saveLocal() { localStorage.setItem(FOLDERS_KEY, JSON.stringify({ folders: state.folders, folderTiles: state.folderTiles })); }
  function escape(value) { const node = document.createElement('span'); node.textContent = value ?? ''; return node.innerHTML; }
  async function json(url, options) { const response = await fetch(url, options); const payload = await response.json().catch(() => ({})); if (!response.ok) throw Object.assign(new Error(payload?.error?.message || 'Ошибка запроса'), { status: response.status }); return payload; }
  async function load() {
    const payload = await json('/api/catalog/tiles.php'); state.items = payload.items || []; state.facets = payload.facets || {}; state.authenticated = Boolean(payload.authenticated);
    state.favorites = new Set(); state.items.filter((item) => item.isFavorite).forEach((item) => state.favorites.add(item.id));
    if (state.authenticated) { const folders = await json('/api/media/folders.php'); state.folders = folders.items || []; await Promise.all(state.folders.map(async (folder) => { const data = await json(`/api/media/folder-tiles.php?folderId=${encodeURIComponent(folder.id)}`); state.folderTiles[folder.id] = data.tileIds || []; })); }
    else { const local = readLocal(FOLDERS_KEY, { folders: [], folderTiles: {} }); state.folders = local.folders || []; state.folderTiles = local.folderTiles || {}; }
    const requestedFolder = new URLSearchParams(window.location.hash.slice(1)).get('folder');
    if (requestedFolder && state.folders.some((folder) => folder.id === requestedFolder)) state.activeFolder = requestedFolder;
    fillFacets(); renderFolders(); render();
  }
  function fillFacets() { const allLabels = { brand:'Все бренды', colors:'Все цвета', sizes:'Все размеры', surfaces:'Все поверхности', designs:'Все дизайны' }; const colorMap = { белый:'#f7f5ef', бежевый:'#d6c1a4', серый:'#8f9298', чёрный:'#303238', черный:'#303238', коричневый:'#896348', голубой:'#91b8d2', синий:'#4f75a2', зелёный:'#77966f', зеленый:'#77966f', розовый:'#c9879e', жёлтый:'#d7b451', желтый:'#d7b451' }; document.querySelectorAll('[data-media-filter]').forEach((group) => { const key = group.dataset.mediaFilter; const facet = group.dataset.facet; const options = group.querySelector('.media-filter-options'); const choice = (value) => key === 'colors' ? `<i class="media-color-swatch" style="background:${colorMap[String(value).toLocaleLowerCase('ru')] || '#c9c4bb'}"></i><span>${escape(value)}</span>` : escape(value); options.innerHTML = `<button type="button" class="is-active" data-filter-value="">${allLabels[key]}</button>${(state.facets[facet] || []).map((value) => `<button type="button" class="${key === 'colors' ? 'media-color-choice' : ''}" data-filter-value="${escape(value)}">${choice(value)}</button>`).join('')}`; }); }
  function filteredItems() {
    const query = $('media-search').value.trim().toLocaleLowerCase('ru'); const filters = state.filters;
    let items = state.items.filter((item) => { if (query && !`${item.name} ${item.shortName || ''} ${item.brand || ''}`.toLocaleLowerCase('ru').includes(query)) return false; return Object.entries(filters).every(([key,value]) => !value || (key === 'brand' ? item.brand === value : (item[key] || []).includes(value))); });
    if (state.activeFolder === 'favorites') items = items.filter((item) => state.favorites.has(item.id)); else if (state.activeFolder !== 'all') items = items.filter((item) => (state.folderTiles[state.activeFolder] || []).includes(item.id));
    return items.sort((a,b) => Number(state.favorites.has(b.id)) - Number(state.favorites.has(a.id)) || (a.shortName || a.name).localeCompare(b.shortName || b.name, 'ru'));
  }
  function render() {
    const items = filteredItems(); $('media-total').textContent = `${state.items.length} плиток в общем каталоге`; $('media-all-count').textContent = state.items.length; $('media-favorite-count').textContent = state.favorites.size; $('media-result-count').textContent = items.length;
    $('media-active-caption').textContent = state.activeFolder === 'all' ? 'Все материалы' : state.activeFolder === 'favorites' ? 'Избранное' : state.folders.find((f) => f.id === state.activeFolder)?.name || 'Папка'; document.querySelectorAll('.media-nav-button').forEach((button) => button.classList.toggle('is-active', button.dataset.folder === state.activeFolder));
    if (!items.length) { $('media-grid').innerHTML = '<div class="media-empty"><strong>Ничего не найдено</strong><p>Измените фильтры или выберите другой раздел.</p></div>'; return; }
    $('media-grid').innerHTML = items.map((tile) => { const favorite = state.favorites.has(tile.id); const image = tile.previewUrl ? `<img src="${escape(tile.previewUrl)}" alt="${escape(tile.shortName || tile.name)}" loading="lazy">` : `<span style="background:${escape(tile.hex)}"></span>`; return `<article class="media-tile-card" data-tile-id="${escape(tile.id)}"><div class="media-tile-image">${image}<button class="media-heart ${favorite ? 'is-favorite' : ''}" type="button" data-favorite>${favorite ? '♥' : '♡'}</button></div><div class="media-tile-copy"><h2>${escape(tile.shortName || tile.name)}</h2><p>${escape(tile.brand || 'Без бренда')}</p><small>${escape((tile.sizes || []).join(', ') || 'Размер не указан')} · ${escape((tile.surfaces || []).join(', ') || 'Поверхность не указана')}</small></div><button class="button button-secondary media-folder-action" type="button" data-add-folder>＋ В папку</button></article>`; }).join('');
  }
  function renderFolders() { $('media-folders').innerHTML = state.folders.length ? state.folders.map((folder) => `<button class="media-nav-button" type="button" data-folder="${escape(folder.id)}"><span>□</span>${escape(folder.name)} <b>${(state.folderTiles[folder.id] || []).length}</b></button>`).join('') : '<small>Папок пока нет</small>'; }
  async function toggleFavorite(tileId) { if (!state.authenticated) { window.alert('Войдите в аккаунт, чтобы пользоваться избранным.'); return; } const adding = !state.favorites.has(tileId); adding ? state.favorites.add(tileId) : state.favorites.delete(tileId); render(); try { await json('/api/favorites/index.php', { method:adding?'PUT':'DELETE', headers:{'Content-Type':'application/json'}, body:JSON.stringify({csrf,entityType:'tile',entityId:tileId}) }); } catch (error) { adding ? state.favorites.delete(tileId) : state.favorites.add(tileId); render(); window.alert(error.message); } }
  async function createFolder(name) { if (state.authenticated) { const payload = await json('/api/media/folders.php', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({csrf,name}) }); state.folders.unshift(payload.item); state.folderTiles[payload.item.id] = []; } else { const folder = { id:crypto.randomUUID(), name, tile_count:0 }; state.folders.unshift(folder); state.folderTiles[folder.id] = []; saveLocal(); } renderFolders(); render(); }
  function openFolderPicker(tileId) { state.selectedTileId = tileId; const tile = state.items.find((item) => item.id === tileId); $('media-add-tile-name').textContent = tile?.shortName || tile?.name || ''; $('media-folder-picker').innerHTML = state.folders.length ? state.folders.map((folder) => { const included = (state.folderTiles[folder.id] || []).includes(tileId); return `<button type="button" data-pick-folder="${escape(folder.id)}" class="${included?'is-selected':''}"><span>□ ${escape(folder.name)}</span><b>${included?'Добавлено ✓':'Добавить'}</b></button>`; }).join('') : '<p>Сначала создайте папку кнопкой «＋» слева.</p>'; $('media-add-dialog').showModal(); }
  async function toggleFolderTile(folderId) { const list = state.folderTiles[folderId] || []; const adding = !list.includes(state.selectedTileId); state.folderTiles[folderId] = adding ? [...list,state.selectedTileId] : list.filter((id) => id !== state.selectedTileId); if (!state.authenticated) saveLocal(); else await json('/api/media/folder-tiles.php', { method:adding?'PUT':'DELETE', headers:{'Content-Type':'application/json'}, body:JSON.stringify({csrf,folderId,tileId:state.selectedTileId}) }); renderFolders(); render(); openFolderPicker(state.selectedTileId); }
  root.addEventListener('click', (event) => { const folder = event.target.closest('[data-folder]'); if (folder) { state.activeFolder = folder.dataset.folder; render(); return; } const card = event.target.closest('[data-tile-id]'); if (!card) return; if (event.target.closest('[data-favorite]')) toggleFavorite(card.dataset.tileId); if (event.target.closest('[data-add-folder]')) openFolderPicker(card.dataset.tileId); });
  document.querySelectorAll('[data-media-panel]').forEach((button) => button.addEventListener('click', () => { const panel = button.dataset.mediaPanel; document.querySelectorAll('[data-media-panel]').forEach((item) => { const active = item === button; item.classList.toggle('is-active', active); item.setAttribute('aria-selected', String(active)); }); document.querySelectorAll('[data-media-panel-content]').forEach((item) => { const active = item.dataset.mediaPanelContent === panel; item.classList.toggle('is-active', active); item.hidden = !active; }); }));
  document.querySelector('.media-sidebar-filters').addEventListener('click', (event) => { const button = event.target.closest('[data-filter-value]'); if (!button) return; const group = button.closest('[data-media-filter]'); state.filters[group.dataset.mediaFilter] = button.dataset.filterValue; group.querySelectorAll('[data-filter-value]').forEach((item) => item.classList.toggle('is-active', item === button)); render(); });
  $('media-search').addEventListener('input', render); $('media-search-button').addEventListener('click', render); $('media-reset').addEventListener('click', () => { $('media-search').value=''; Object.keys(state.filters).forEach((key) => state.filters[key]=''); document.querySelectorAll('[data-media-filter]').forEach((group) => group.querySelectorAll('[data-filter-value]').forEach((button) => button.classList.toggle('is-active', button.dataset.filterValue === ''))); render(); });
  $('media-add-folder').addEventListener('click', () => $('media-folder-dialog').showModal()); $('media-folder-form').addEventListener('submit', async (event) => { event.preventDefault(); const name=$('media-folder-name').value.trim(); if (!name) return; try { await createFolder(name); $('media-folder-name').value=''; $('media-folder-dialog').close(); } catch(error) { window.alert(error.message); } }); $('media-folder-picker').addEventListener('click', (event) => { const button=event.target.closest('[data-pick-folder]'); if (button) toggleFolderTile(button.dataset.pickFolder).catch((error)=>window.alert(error.message)); }); document.querySelector('[data-close-folder-picker]').addEventListener('click', () => $('media-add-dialog').close());
  const adminAdd = $('media-admin-add'); const adminDialog = $('media-admin-dialog'); const adminForm = $('media-admin-form');
  if (adminAdd && adminDialog && adminForm) {
    adminAdd.addEventListener('click', () => adminDialog.showModal());
    adminDialog.querySelector('[data-close-admin-tile]')?.addEventListener('click', () => adminDialog.close());
    adminForm.addEventListener('submit', async (event) => {
      event.preventDefault();
      const submit = adminForm.querySelector('[type="submit"]'); const errorNode = $('media-admin-error');
      submit.disabled = true; errorNode.hidden = true;
      try {
        const response = await fetch('/api/admin/catalog-tiles.php', { method:'POST', headers:{'X-CSRF-Token':csrf}, body:new FormData(adminForm) });
        const payload = await response.json().catch(() => ({}));
        if (!response.ok) throw new Error(payload?.error?.message || 'Не удалось добавить товар.');
        window.location.reload();
      } catch (error) {
        errorNode.textContent = error.message; errorNode.hidden = false; submit.disabled = false;
      }
    });
  }
  load().catch((error) => { $('media-grid').innerHTML = `<div class="media-empty"><strong>Каталог временно недоступен</strong><p>${escape(error.message)}</p></div>`; });
})();
